apiVersion: v1
kind: LimitRange
metadata:
  name: demo-exchange-limit-range
  namespace: demo-exchange
spec:
  limits:
  - default:
      cpu: 8000m
      memory: 15.5G
    defaultRequest:
      cpu: 600m
      memory: 512M
    type: Container