server:
  port: 5001
  servlet:
    context-path: /${match-engine.base}-${match-engine.quote}

match-engine:
  base: BTC
  quote: USDT
  symbol: ${match-engine.base}-${match-engine.quote}
  maker-fee: 5 # percent
  taker-fee: 5 # percent
  base-scale: 18 # caution: this value should never be changed once deployed
  quote-scale: 18 # caution: this value should never be changed once deployed
  base-tick: 1000000000000000000 # caution: this value should never be changed once deployed (10**scale)
  quote-tick: 1000000000000000000 # caution: this value should never be changed once deployed (10**scale)
  match-engine-url: http://localhost:${server.port}

spring:
  application:
    name: service-match-engine-${match-engine.base}-${match-engine.quote}
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/demo_exchange
    username: demo_exchange
    password: demo_exchange_secret
  rabbitmq:
    addresses: localhost
    username: mq_user
    password: mq_password
    ssl:
      enabled: false

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
