
server:
  port: 5003

service-user:
  match-engine-url: http://localhost:5001

spring:
  application:
    name: service-user
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/demo_exchange
    username: demo_exchange
    password: demo_exchange_secret
  rabbitmq:
    addresses: localhost
    username: mq_user
    password: mq_password
    ssl:
      enabled: false

